-- =============================================================
-- SentinelDB - Oracle customer authentication extension
-- =============================================================

WHENEVER SQLERROR EXIT SQL.SQLCODE;

ALTER SESSION SET CONTAINER=FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA=SENTINELDB;

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE customer_accounts (
            customer_account_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            email               VARCHAR2(255) NOT NULL UNIQUE,
            password_hash       VARCHAR2(64)  NOT NULL,
            customer_id         NUMBER(10)    NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
            is_active           NUMBER(1)     DEFAULT 1 NOT NULL CHECK (is_active IN (0, 1)),
            created_at          TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
            last_login_at       TIMESTAMP
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE customer_sessions (
            session_id          NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            customer_account_id NUMBER(10)    NOT NULL REFERENCES customer_accounts(customer_account_id) ON DELETE CASCADE,
            token_hash          VARCHAR2(64)  NOT NULL UNIQUE,
            expires_at          TIMESTAMP     NOT NULL,
            ip_address          VARCHAR2(45),
            created_at          TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
            is_active           NUMBER(1)     DEFAULT 1 NOT NULL CHECK (is_active IN (0, 1)),
            CONSTRAINT chk_customer_session_expiry CHECK (expires_at > created_at)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

CREATE OR REPLACE FUNCTION fn_customer_signup(
    p_email        IN VARCHAR2,
    p_password_md5 IN VARCHAR2,
    p_full_name    IN VARCHAR2,
    p_phone        IN VARCHAR2 DEFAULT NULL,
    p_ip_address   IN VARCHAR2 DEFAULT NULL
) RETURN SYS_REFCURSOR
AS
    v_existing_count NUMBER;
    v_customer_id    customers.customer_id%TYPE;
    v_account_id     customer_accounts.customer_account_id%TYPE;
    v_token          VARCHAR2(64);
    v_expires        TIMESTAMP;
    v_result         SYS_REFCURSOR;
BEGIN
    SELECT COUNT(*)
    INTO   v_existing_count
    FROM   customer_accounts
    WHERE  email = p_email;

    IF v_existing_count > 0 THEN
        raise_application_error(-20011, 'SIGNUP_FAIL: an account with this email already exists');
    END IF;

    BEGIN
        SELECT customer_id
        INTO   v_customer_id
        FROM   customers
        WHERE  email = p_email
        FETCH FIRST 1 ROWS ONLY;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO customers (name, email, phone)
            VALUES (p_full_name, p_email, p_phone)
            RETURNING customer_id INTO v_customer_id;
    END;

    INSERT INTO customer_accounts (email, password_hash, customer_id)
    VALUES (p_email, p_password_md5, v_customer_id)
    RETURNING customer_account_id INTO v_account_id;

    v_token := LOWER(RAWTOHEX(SYS_GUID()));
    v_expires := CAST(SYSTIMESTAMP AS TIMESTAMP) + INTERVAL '24' HOUR;

    INSERT INTO customer_sessions (customer_account_id, token_hash, expires_at, ip_address)
    VALUES (v_account_id, v_token, v_expires, p_ip_address);

    OPEN v_result FOR
        SELECT v_token AS out_token,
               v_expires AS out_expires,
               v_customer_id AS out_customer_id,
               c.name AS out_full_name,
               c.phone AS out_phone
        FROM   customers c
        WHERE  c.customer_id = v_customer_id;

    RETURN v_result;
END;
/

CREATE OR REPLACE FUNCTION fn_customer_login(
    p_email        IN VARCHAR2,
    p_password_md5 IN VARCHAR2,
    p_ip_address   IN VARCHAR2 DEFAULT NULL
) RETURN SYS_REFCURSOR
AS
    v_account_id  customer_accounts.customer_account_id%TYPE;
    v_customer_id customer_accounts.customer_id%TYPE;
    v_is_active   customer_accounts.is_active%TYPE;
    v_token       VARCHAR2(64);
    v_expires     TIMESTAMP;
    v_result      SYS_REFCURSOR;
BEGIN
    BEGIN
        SELECT ca.customer_account_id, ca.customer_id, ca.is_active
        INTO   v_account_id, v_customer_id, v_is_active
        FROM   customer_accounts ca
        WHERE  ca.email = p_email
          AND  ca.password_hash = p_password_md5;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            raise_application_error(-20012, 'AUTH_FAIL: invalid email or password');
    END;

    IF v_is_active <> 1 THEN
        raise_application_error(-20013, 'AUTH_FAIL: account is disabled');
    END IF;

    v_token := LOWER(RAWTOHEX(SYS_GUID()));
    v_expires := CAST(SYSTIMESTAMP AS TIMESTAMP) + INTERVAL '24' HOUR;

    UPDATE customer_sessions
    SET    is_active = 0
    WHERE  customer_account_id = v_account_id
      AND  is_active = 1;

    INSERT INTO customer_sessions (customer_account_id, token_hash, expires_at, ip_address)
    VALUES (v_account_id, v_token, v_expires, p_ip_address);

    UPDATE customer_accounts
    SET    last_login_at = CAST(SYSTIMESTAMP AS TIMESTAMP)
    WHERE  customer_account_id = v_account_id;

    OPEN v_result FOR
        SELECT v_token AS out_token,
               v_expires AS out_expires,
               v_customer_id AS out_customer_id,
               c.name AS out_full_name,
               c.phone AS out_phone
        FROM   customers c
        WHERE  c.customer_id = v_customer_id;

    RETURN v_result;
END;
/

CREATE OR REPLACE FUNCTION fn_customer_validate_session(
    p_token_hash IN VARCHAR2
) RETURN SYS_REFCURSOR
AS
    v_result SYS_REFCURSOR;
BEGIN
    OPEN v_result FOR
        SELECT ca.customer_account_id AS out_customer_account_id,
               ca.customer_id AS out_customer_id,
               ca.email AS out_email,
               c.name AS out_full_name,
               c.phone AS out_phone
        FROM   customer_sessions cs
        JOIN   customer_accounts ca ON ca.customer_account_id = cs.customer_account_id
        JOIN   customers         c  ON c.customer_id          = ca.customer_id
        WHERE  cs.token_hash = p_token_hash
          AND  cs.is_active  = 1
          AND  cs.expires_at > CAST(SYSTIMESTAMP AS TIMESTAMP)
          AND  ca.is_active  = 1;

    RETURN v_result;
END;
/

CREATE OR REPLACE FUNCTION fn_customer_logout(
    p_token_hash IN VARCHAR2
) RETURN NUMBER
AS
BEGIN
    UPDATE customer_sessions
    SET    is_active = 0
    WHERE  token_hash = p_token_hash
      AND  is_active = 1;

    IF SQL%ROWCOUNT > 0 THEN
        RETURN 1;
    END IF;

    RETURN 0;
END;
/
