-- =============================================================
-- SentinelDB - Oracle table schema
-- =============================================================

WHENEVER SQLERROR EXIT SQL.SQLCODE;

ALTER SESSION SET CONTAINER=FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA=SENTINELDB;

-- ACCOUNT MODULE

CREATE TABLE roles (
    role_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR2(50)  NOT NULL UNIQUE,
    description CLOB,
    can_admin   NUMBER(1)     DEFAULT 0 NOT NULL CHECK (can_admin IN (0, 1)),
    can_sales   NUMBER(1)     DEFAULT 0 NOT NULL CHECK (can_sales IN (0, 1)),
    can_stock   NUMBER(1)     DEFAULT 0 NOT NULL CHECK (can_stock IN (0, 1)),
    can_view    NUMBER(1)     DEFAULT 1 NOT NULL CHECK (can_view IN (0, 1)),
    created_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE users (
    user_id       NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(100) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role_id       NUMBER(10)    NOT NULL REFERENCES roles(role_id),
    is_active     NUMBER(1)     DEFAULT 1 NOT NULL CHECK (is_active IN (0, 1)),
    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_login    TIMESTAMP
);

CREATE TABLE sessions (
    session_id  NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id     NUMBER(10)    NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token_hash  VARCHAR2(255) NOT NULL UNIQUE,
    created_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at  TIMESTAMP     NOT NULL,
    ip_address  VARCHAR2(45),
    is_active   NUMBER(1)     DEFAULT 1 NOT NULL CHECK (is_active IN (0, 1)),
    CONSTRAINT chk_session_expiry CHECK (expires_at > created_at)
);

-- STOCK MODULE

CREATE TABLE categories (
    category_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL UNIQUE,
    description CLOB,
    created_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE suppliers (
    supplier_id  NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name         VARCHAR2(150) NOT NULL,
    contact_name VARCHAR2(100),
    phone        VARCHAR2(20),
    email        VARCHAR2(150),
    address      CLOB,
    created_at   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE products (
    product_id  NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(150) NOT NULL,
    category_id NUMBER(10)    REFERENCES categories(category_id) ON DELETE SET NULL,
    price       NUMBER(10,2)  NOT NULL CHECK (price >= 0),
    stock_qty   NUMBER(10)    DEFAULT 0 NOT NULL CHECK (stock_qty >= 0),
    supplier_id NUMBER(10)    REFERENCES suppliers(supplier_id) ON DELETE SET NULL,
    image_url   VARCHAR2(500),
    is_active   NUMBER(1)     DEFAULT 1 NOT NULL CHECK (is_active IN (0, 1)),
    created_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE product_images (
    image_id   NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    label      VARCHAR2(150) NOT NULL,
    image_url  VARCHAR2(500) NOT NULL UNIQUE,
    source     CLOB,
    created_at TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- SALES MODULE

CREATE TABLE customers (
    customer_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(150) NOT NULL,
    phone       VARCHAR2(20),
    email       VARCHAR2(150),
    address     CLOB,
    created_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE orders (
    order_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_id  NUMBER(10)   REFERENCES customers(customer_id) ON DELETE SET NULL,
    user_id      NUMBER(10)   REFERENCES users(user_id),
    total_amount NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (total_amount >= 0),
    status       VARCHAR2(20) DEFAULT 'pending' NOT NULL
                     CHECK (status IN ('pending', 'confirmed', 'shipped', 'completed', 'cancelled')),
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE order_items (
    item_id    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id   NUMBER(10)   NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id NUMBER(10)   NOT NULL REFERENCES products(product_id),
    quantity   NUMBER(10)   NOT NULL CHECK (quantity > 0),
    unit_price NUMBER(10,2) NOT NULL CHECK (unit_price >= 0),
    subtotal   NUMBER(12,2) GENERATED ALWAYS AS (quantity * unit_price) VIRTUAL
);

CREATE TABLE invoices (
    invoice_id  NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id    NUMBER(10)   NOT NULL UNIQUE REFERENCES orders(order_id),
    issued_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    due_date    DATE,
    paid_at     TIMESTAMP,
    status      VARCHAR2(20) DEFAULT 'unpaid' NOT NULL
                    CHECK (status IN ('unpaid', 'paid', 'overdue', 'cancelled')),
    notes       CLOB
);

-- ADMIN MODULE

CREATE TABLE audit_logs (
    log_id         NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id        NUMBER(10)   REFERENCES users(user_id) ON DELETE SET NULL,
    action         VARCHAR2(50) NOT NULL,
    table_affected VARCHAR2(100),
    record_id      NUMBER(10),
    old_value      CLOB CHECK (old_value IS JSON),
    new_value      CLOB CHECK (new_value IS JSON),
    ip_address     VARCHAR2(45),
    timestamp      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE system_config (
    config_id    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    config_key   VARCHAR2(100) NOT NULL UNIQUE,
    config_value CLOB          NOT NULL,
    description  CLOB,
    updated_at   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by   NUMBER(10)    REFERENCES users(user_id) ON DELETE SET NULL
);
